SELECT TOP 3
    CASE 
        WHEN FINALIZADORAS.TIPO = '1' THEN 'DINHEIRO'
        WHEN FINALIZADORAS.TIPO = '4' THEN 'CARTÃO'
        WHEN FINALIZADORAS.TIPO = '5' THEN 'CONVÊNIO'
        WHEN FINALIZADORAS.TIPO = '8' THEN 'PIX'
        ELSE 'OUTROS'
    END AS [FORMA DE PAGAMENTO],

    CASE 
        WHEN FINALIZADORAS.STATUS = 'A' THEN 'APROVADA'
        ELSE 'CANCELADA'
    END AS [STATUS COMPRA], 

    FINALIZADORAS.VALOR AS [VALOR PAGO],
    FINALIZADORAS.TROCO AS [TROCO],
    FINALIZADORAS.ECF_CUPOM AS [CUPOM],
    FINALIZADORAS.NSU AS [NSU],
    FINALIZADORAS.VENDA AS [Nº VENDA]
FROM 
    FINALIZADORAS
WHERE 
    FINALIZADORAS.MOVIMENTO = ? AND FINALIZADORAS.VALOR = ?
ORDER BY 
    FINALIZADORAS.VENDA DESC;
