CREATE PROCEDURE USP_SINCRONIZA_TABELAS_PDV_LOJA  
(  
 @SQL   NVARCHAR(MAX) = NULL  
  , @INDEX_WHILE INT     = 1  
  , @TABLE_NAME NVARCHAR(255)  = NULL  
)  
AS  
BEGIN  
  
 SET NOCOUNT ON;  
  
 IF OBJECT_ID ( 'TABELA_SYNC_BALCAO_PDV','U' ) IS NOT NULL  
 DROP TABLE TABELA_SYNC_BALCAO_PDV  
  
 CREATE TABLE TABELA_SYNC_BALCAO_PDV ( ID INT  
          , TABELA NVARCHAR(200))  
  
 INSERT INTO TABELA_SYNC_BALCAO_PDV ( ID   
           , TABELA)  
  
    VALUES  
  (1,'ADQUIRENTES')  
 ,(2,'BANDEIRAS')  
 ,(3,'BIOMETRIAS')  
 ,(4,'CARTOES_FAMILIAS')  
 ,(5,'CARTOES_GRUPOS')  
 ,(6,'CARTOES_PRODUTOS')  
 ,(7,'CARTOES_SECOES')  
 ,(8,'CARTOES_SUBGRUPOS')  
 ,(9,'CODIGOS_BANDEIRAS')  
 ,(10,'CONVENIOS_GRUPOS')  
 ,(11,'CONVENIOS_MARCAS')  
 ,(12,'CONVENIOS_PRODUTOS')  
 ,(13,'CONVENIOS_PROMOCIONAIS')  
 ,(14,'CONVENIOS_PROMOCIONAIS_CLASSES')  
 ,(15,'CONVENIOS_PROMOCIONAIS_GRUPOS')  
 ,(16,'CONVENIOS_PROMOCIONAIS_MARCAS')  
 ,(17,'CONVENIOS_PROMOCIONAIS_PRODUTOS')  
 ,(18,'CONVENIOS_PROMOCIONAIS_SECOES')  
 ,(19,'CONVENIOS_PROMOCIONAIS_SUBGRUPOS')  
 ,(20,'CONVENIOS_SECOES')  
 ,(21,'CONVENIOS_SUBGRUPOS')  
 ,(22,'CORRELATOS')  
 ,(23,'CR_PRESCRITOR')  
 ,(24,'CUSTO')  
 ,(25,'DESCONTOS_PROGRESSIVOS')  
 ,(26,'DESCONTOS_PROGRESSIVOS_PROMOCOES')  
 ,(27,'EAN')  
 ,(28,'ESTADOS')  
 ,(29,'FPOPULAR_PERIODOS_DISPENSACOES')  
 ,(30,'MAQUINAS_POS')  
 ,(31,'MEDICOS')  
 ,(32,'MOEDAS')  
 ,(33,'MOEDAS_CONVERSOES')  
 ,(34,'OPERADORES')  
 ,(35,'PRODUTOS')  
 ,(36,'PRODUTOS_COMPOSICOES')  
 ,(37,'REGRAS_GERAR_VALES_PRESENTES_PDV')  
 ,(38,'REGRAS_GERAR_VALES_PRESENTES_PDV_GRUPOS')  
 ,(39,'REGRAS_GERAR_VALES_PRESENTES_PDV_PRODUTOS')  
 ,(40,'REGRAS_GERAR_VALES_PRESENTES_PDV_SECOES')  
 ,(41,'REGRAS_GERAR_VALES_PRESENTES_PDV_SUBGRUPOS')  
 ,(42,'SERVICOS')  
 ,(43,'SUBSTITUTOS')  
 ,(44,'TABELA_VALORES_RECARGAS')  
 ,(45,'TABELAS_DESCONTOS')  
 ,(46,'TABELAS_ENCARTES')  
 ,(47,'TAMANHOS_PRODUTOS')  
 ,(48,'TIPOS_CANCELAMENTOS')  
 ,(49,'TIPOS_SANGRIAS')  
 ,(50,'TIPOS_TOTALIZADORES_NT')  
  
  
  
 SELECT TOP 1 @INDEX_WHILE = MIN (ID)  
   FROM TABELA_SYNC_BALCAO_PDV  
  
  
 WHILE @INDEX_WHILE IS NOT NULL   
 BEGIN   
    
  SELECT TOP 1 @TABLE_NAME = TABELA   
    FROM TABELA_SYNC_BALCAO_PDV  
   WHERE ID = @INDEX_WHILE  
  
  
  BEGIN TRY   
  
   EXEC ('  
     
    TRUNCATE TABLE ' + @TABLE_NAME + '  
      INSERT INTO  ' + @TABLE_NAME + '   
      SELECT TOP 1   
       *   
     FROM [BALCAO].[LOJA].[dbo].[' + @TABLE_NAME + ']  
  
   ')  
  
  END TRY   
  BEGIN CATCH   
  
   EXEC ('  
  
   DECLARE @SQL NVARCHAR(MAX)  
  
  
   DROP TABLE IF EXISTS #' + @TABLE_NAME + ';  
   
   SELECT TOP 1   
       *   
     INTO #' + @TABLE_NAME + '      
     FROM [BALCAO].[LOJA].[dbo].[' + @TABLE_NAME + ']  
    WHERE 1 = 2  
  
     
   IF EXISTS ( SELECT TOP 1 1 FROM sys.objects WHERE object_id = OBJECT_ID(N''[dbo].[' + @TABLE_NAME + ']'') AND type IN (N''U'') )  
    DROP TABLE [dbo].[' + @TABLE_NAME + '];  
  
  
   SELECT @SQL = DBO.FN_TABLE_STRUCTURE_PDV(''SELECT * FROM #' + @TABLE_NAME + ''', ''' +  @TABLE_NAME + ''')  
   EXEC ( @SQL )   
  
    ')  
  
  END CATCH   
  
  
  SET @INDEX_WHILE = ( SELECT MIN (ID) FROM TABELA_SYNC_BALCAO_PDV WHERE ID > @INDEX_WHILE )  
  
 END  
  
  
 SET NOCOUNT OFF;  
  
END